// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9F313eKG3pYenvNW-c2Ttv1_qhWwlxXw',
    appId: '1:769927556035:web:67ffde6abd020c5e3e2b76',
    messagingSenderId: '769927556035',
    projectId: 'santos-rentacar',
    authDomain: 'santos-rentacar.firebaseapp.com',
    storageBucket: 'santos-rentacar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb9Jt7aS3TMO8viXwfNRACfYjAd6nomdE',
    appId: '1:769927556035:android:e294fcf1111b00773e2b76',
    messagingSenderId: '769927556035',
    projectId: 'santos-rentacar',
    storageBucket: 'santos-rentacar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgZKU1XE2Esd9-FqrTu7s2_hetlj4L7EE',
    appId: '1:769927556035:ios:f4696468e125b2443e2b76',
    messagingSenderId: '769927556035',
    projectId: 'santos-rentacar',
    storageBucket: 'santos-rentacar.firebasestorage.app',
    iosBundleId: 'com.example.santosRentacar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgZKU1XE2Esd9-FqrTu7s2_hetlj4L7EE',
    appId: '1:769927556035:ios:f4696468e125b2443e2b76',
    messagingSenderId: '769927556035',
    projectId: 'santos-rentacar',
    storageBucket: 'santos-rentacar.firebasestorage.app',
    iosBundleId: 'com.example.santosRentacar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9F313eKG3pYenvNW-c2Ttv1_qhWwlxXw',
    appId: '1:769927556035:web:212bed634fe224883e2b76',
    messagingSenderId: '769927556035',
    projectId: 'santos-rentacar',
    authDomain: 'santos-rentacar.firebaseapp.com',
    storageBucket: 'santos-rentacar.firebasestorage.app',
  );
}
